- name: Setup DHCP leases for OVN ports
  hosts: ovirt_engine
  gather_facts: false

  vars:
    port_id: "{{ port_id | regex_replace('[^a-z0-9_]', '') }}"
    mac_address: >-
      {{
        mac_address | regex_replace('^(?:[0-9A-Fa-f]{2}[:-]){5}(?:[0-9A-Fa-f]{2})$', '\\0')
                     | default('')
      }}
    ip_address: >-
      {{
        ip_address | regex_replace('^(?:\\d{1,3}\\.){3}\\d{1,3}$', '\\0')
                    | default('')
      }}

  tasks:
    - name: Create DHCP Lease
      ansible.builtin.shell: >
        ovn-nbctl set logical_switch_port "{{ port_id }}" dynamic_addresses="\"{{ mac_address }} {{ ip_address }}\""
      register: success
      changed_when: success.rc == 0
