---
- hosts: ovirt_engine
  gather_facts: no
  tasks:
  - name: Reset VM password
    shell: >
      ssh -i /etc/pki/ovirt-engine/keys/engine_id_rsa -o StrictHostKeyChecking=no root@{{ host }} 'virsh -c qemu:///system?authfile=/etc/ovirt-hosted-engine/virsh_auth.conf set-user-password "{{ vm_name }}" "{{ username }}" "{{ password }}"'
